version: '3.8'

services:
  backend:
    build: .
    container_name: shoppit-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ADMIN_PASSWORD: admin123

      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shoppit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: shoppit
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
